name: Run systemd in Docker and test with pytest

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t systemd-container .

      - name: Run container in background
        run: docker run --privileged -d --name my-container -v /sys/fs/cgroup:/sys/fs/cgroup:ro systemd-container

      - name: Run tests with pytest
        run: docker exec my-container bash -c "cd /app && poetry run pytest"
